POST http://localhost:3000/api/files/upload
Content-Type: multipart/form-data

---
### This is a separator. Everything above is the request header, everything below is the request body.

Content-Disposition: form-data; name="file"; filename="FileServerProject-Node2023.pdf"
Content-Type: application/pdf

@../FileServerProject-Node2023.pdf
